name: Deployment

on:
    push:
        branches: ['master']
    pull_request:
        # TODO : juste pour tester !!!
        branches: ['**']
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository files
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 18.17.0
                  cache: npm

            - name: Install dependencies
              run: yarn --frozen-lockfile

            - name: Build application
              run: yarn build

            - name: Upload artifacts
              run: actions/upload-pages-artifact@v3
              with:
                  path: ./dist/online-resume
                  name: github-pages
                  retention-days: 1
